
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Icons Index</title>
      <style>
        @import url(//fonts.googleapis.com/css?family=RobotoDraft&lang=en);
        body {
          font-family:'RobotoDraft', Arial, sans-serif;
          font-size: 10px;
        }
        img {
          width: 48px;
          height: 48px;
        }
        div {
          width: 54px;
          display:inline-block;
          text-align:center;
          white-space:wrap;
          vertical-align:top;
          padding:4px;
        }
        h1, h2 {
          padding:12px;
        }
      </style>
  </head>
  <body>
  <h1>Material Icons</h1>


<h1>action</h1>
<div><img src='./action/ic_3d_rotation_black_24dp.png'><br>3d rotation</div>
<div><img src='./action/ic_accessibility_black_24dp.png'><br>accessibility</div>
<div><img src='./action/ic_account_balance_black_24dp.png'><br>account balance</div>
<div><img src='./action/ic_account_balance_wallet_black_24dp.png'><br>account balance wallet</div>
<div><img src='./action/ic_account_box_black_24dp.png'><br>account box</div>
<div><img src='./action/ic_account_child_black_24dp.png'><br>account child</div>
<div><img src='./action/ic_account_circle_black_24dp.png'><br>account circle</div>
<div><img src='./action/ic_add_shopping_cart_black_24dp.png'><br>add shopping cart</div>
<div><img src='./action/ic_alarm_black_24dp.png'><br>alarm</div>
<div><img src='./action/ic_alarm_add_black_24dp.png'><br>alarm add</div>
<div><img src='./action/ic_alarm_off_black_24dp.png'><br>alarm off</div>
<div><img src='./action/ic_alarm_on_black_24dp.png'><br>alarm on</div>
<div><img src='./action/ic_android_black_24dp.png'><br>android</div>
<div><img src='./action/ic_announcement_black_24dp.png'><br>announcement</div>
<div><img src='./action/ic_aspect_ratio_black_24dp.png'><br>aspect ratio</div>
<div><img src='./action/ic_assessment_black_24dp.png'><br>assessment</div>
<div><img src='./action/ic_assignment_black_24dp.png'><br>assignment</div>
<div><img src='./action/ic_assignment_ind_black_24dp.png'><br>assignment ind</div>
<div><img src='./action/ic_assignment_late_black_24dp.png'><br>assignment late</div>
<div><img src='./action/ic_assignment_return_black_24dp.png'><br>assignment return</div>
<div><img src='./action/ic_assignment_returned_black_24dp.png'><br>assignment returned</div>
<div><img src='./action/ic_assignment_turned_in_black_24dp.png'><br>assignment turned in</div>
<div><img src='./action/ic_autorenew_black_24dp.png'><br>autorenew</div>
<div><img src='./action/ic_backup_black_24dp.png'><br>backup</div>
<div><img src='./action/ic_book_black_24dp.png'><br>book</div>
<div><img src='./action/ic_bookmark_black_24dp.png'><br>bookmark</div>
<div><img src='./action/ic_bookmark_outline_black_24dp.png'><br>bookmark outline</div>
<div><img src='./action/ic_bug_report_black_24dp.png'><br>bug report</div>
<div><img src='./action/ic_cached_black_24dp.png'><br>cached</div>
<div><img src='./action/ic_class_black_24dp.png'><br>class</div>
<div><img src='./action/ic_credit_card_black_24dp.png'><br>credit card</div>
<div><img src='./action/ic_dashboard_black_24dp.png'><br>dashboard</div>
<div><img src='./action/ic_delete_black_24dp.png'><br>delete</div>
<div><img src='./action/ic_description_black_24dp.png'><br>description</div>
<div><img src='./action/ic_dns_black_24dp.png'><br>dns</div>
<div><img src='./action/ic_done_black_24dp.png'><br>done</div>
<div><img src='./action/ic_done_all_black_24dp.png'><br>done all</div>
<div><img src='./action/ic_event_black_24dp.png'><br>event</div>
<div><img src='./action/ic_exit_to_app_black_24dp.png'><br>exit to app</div>
<div><img src='./action/ic_explore_black_24dp.png'><br>explore</div>
<div><img src='./action/ic_extension_black_24dp.png'><br>extension</div>
<div><img src='./action/ic_face_unlock_black_24dp.png'><br>face unlock</div>
<div><img src='./action/ic_favorite_black_24dp.png'><br>favorite</div>
<div><img src='./action/ic_favorite_outline_black_24dp.png'><br>favorite outline</div>
<div><img src='./action/ic_find_in_page_black_24dp.png'><br>find in page</div>
<div><img src='./action/ic_find_replace_black_24dp.png'><br>find replace</div>
<div><img src='./action/ic_flip_to_back_black_24dp.png'><br>flip to back</div>
<div><img src='./action/ic_flip_to_front_black_24dp.png'><br>flip to front</div>
<div><img src='./action/ic_get_app_black_24dp.png'><br>get app</div>
<div><img src='./action/ic_grade_black_24dp.png'><br>grade</div>
<div><img src='./action/ic_group_work_black_24dp.png'><br>group work</div>
<div><img src='./action/ic_help_black_24dp.png'><br>help</div>
<div><img src='./action/ic_highlight_remove_black_24dp.png'><br>highlight remove</div>
<div><img src='./action/ic_history_black_24dp.png'><br>history</div>
<div><img src='./action/ic_home_black_24dp.png'><br>home</div>
<div><img src='./action/ic_https_black_24dp.png'><br>https</div>
<div><img src='./action/ic_info_black_24dp.png'><br>info</div>
<div><img src='./action/ic_info_outline_black_24dp.png'><br>info outline</div>
<div><img src='./action/ic_input_black_24dp.png'><br>input</div>
<div><img src='./action/ic_invert_colors_black_24dp.png'><br>invert colors</div>
<div><img src='./action/ic_label_black_24dp.png'><br>label</div>
<div><img src='./action/ic_label_outline_black_24dp.png'><br>label outline</div>
<div><img src='./action/ic_language_black_24dp.png'><br>language</div>
<div><img src='./action/ic_launch_black_24dp.png'><br>launch</div>
<div><img src='./action/ic_list_black_24dp.png'><br>list</div>
<div><img src='./action/ic_lock_black_24dp.png'><br>lock</div>
<div><img src='./action/ic_lock_open_black_24dp.png'><br>lock open</div>
<div><img src='./action/ic_lock_outline_black_24dp.png'><br>lock outline</div>
<div><img src='./action/ic_loyalty_black_24dp.png'><br>loyalty</div>
<div><img src='./action/ic_markunread_mailbox_black_24dp.png'><br>markunread mailbox</div>
<div><img src='./action/ic_note_add_black_24dp.png'><br>note add</div>
<div><img src='./action/ic_open_in_browser_black_24dp.png'><br>open in browser</div>
<div><img src='./action/ic_open_in_new_black_24dp.png'><br>open in new</div>
<div><img src='./action/ic_open_with_black_24dp.png'><br>open with</div>
<div><img src='./action/ic_pageview_black_24dp.png'><br>pageview</div>
<div><img src='./action/ic_payment_black_24dp.png'><br>payment</div>
<div><img src='./action/ic_perm_camera_mic_black_24dp.png'><br>perm camera mic</div>
<div><img src='./action/ic_perm_contact_cal_black_24dp.png'><br>perm contact cal</div>
<div><img src='./action/ic_perm_data_setting_black_24dp.png'><br>perm data setting</div>
<div><img src='./action/ic_perm_device_info_black_24dp.png'><br>perm device info</div>
<div><img src='./action/ic_perm_identity_black_24dp.png'><br>perm identity</div>
<div><img src='./action/ic_perm_media_black_24dp.png'><br>perm media</div>
<div><img src='./action/ic_perm_phone_msg_black_24dp.png'><br>perm phone msg</div>
<div><img src='./action/ic_perm_scan_wifi_black_24dp.png'><br>perm scan wifi</div>
<div><img src='./action/ic_picture_in_picture_black_24dp.png'><br>picture in picture</div>
<div><img src='./action/ic_polymer_black_24dp.png'><br>polymer</div>
<div><img src='./action/ic_print_black_24dp.png'><br>print</div>
<div><img src='./action/ic_query_builder_black_24dp.png'><br>query builder</div>
<div><img src='./action/ic_question_answer_black_24dp.png'><br>question answer</div>
<div><img src='./action/ic_receipt_black_24dp.png'><br>receipt</div>
<div><img src='./action/ic_redeem_black_24dp.png'><br>redeem</div>
<div><img src='./action/ic_reorder_black_24dp.png'><br>reorder</div>
<div><img src='./action/ic_report_problem_black_24dp.png'><br>report problem</div>
<div><img src='./action/ic_restore_black_24dp.png'><br>restore</div>
<div><img src='./action/ic_room_black_24dp.png'><br>room</div>
<div><img src='./action/ic_schedule_black_24dp.png'><br>schedule</div>
<div><img src='./action/ic_search_black_24dp.png'><br>search</div>
<div><img src='./action/ic_settings_black_24dp.png'><br>settings</div>
<div><img src='./action/ic_settings_applications_black_24dp.png'><br>settings applications</div>
<div><img src='./action/ic_settings_backup_restore_black_24dp.png'><br>settings backup restore</div>
<div><img src='./action/ic_settings_bluetooth_black_24dp.png'><br>settings bluetooth</div>
<div><img src='./action/ic_settings_cell_black_24dp.png'><br>settings cell</div>
<div><img src='./action/ic_settings_display_black_24dp.png'><br>settings display</div>
<div><img src='./action/ic_settings_ethernet_black_24dp.png'><br>settings ethernet</div>
<div><img src='./action/ic_settings_input_antenna_black_24dp.png'><br>settings input antenna</div>
<div><img src='./action/ic_settings_input_component_black_24dp.png'><br>settings input component</div>
<div><img src='./action/ic_settings_input_composite_black_24dp.png'><br>settings input composite</div>
<div><img src='./action/ic_settings_input_hdmi_black_24dp.png'><br>settings input hdmi</div>
<div><img src='./action/ic_settings_input_svideo_black_24dp.png'><br>settings input svideo</div>
<div><img src='./action/ic_settings_overscan_black_24dp.png'><br>settings overscan</div>
<div><img src='./action/ic_settings_phone_black_24dp.png'><br>settings phone</div>
<div><img src='./action/ic_settings_power_black_24dp.png'><br>settings power</div>
<div><img src='./action/ic_settings_remote_black_24dp.png'><br>settings remote</div>
<div><img src='./action/ic_settings_voice_black_24dp.png'><br>settings voice</div>
<div><img src='./action/ic_shop_black_24dp.png'><br>shop</div>
<div><img src='./action/ic_shop_two_black_24dp.png'><br>shop two</div>
<div><img src='./action/ic_shopping_basket_black_24dp.png'><br>shopping basket</div>
<div><img src='./action/ic_shopping_cart_black_24dp.png'><br>shopping cart</div>
<div><img src='./action/ic_speaker_notes_black_24dp.png'><br>speaker notes</div>
<div><img src='./action/ic_spellcheck_black_24dp.png'><br>spellcheck</div>
<div><img src='./action/ic_star_rate_black_24dp.png'><br>star rate</div>
<div><img src='./action/ic_stars_black_24dp.png'><br>stars</div>
<div><img src='./action/ic_store_black_24dp.png'><br>store</div>
<div><img src='./action/ic_subject_black_24dp.png'><br>subject</div>
<div><img src='./action/ic_supervisor_account_black_24dp.png'><br>supervisor account</div>
<div><img src='./action/ic_swap_horiz_black_24dp.png'><br>swap horiz</div>
<div><img src='./action/ic_swap_vert_black_24dp.png'><br>swap vert</div>
<div><img src='./action/ic_swap_vert_circle_black_24dp.png'><br>swap vert circle</div>
<div><img src='./action/ic_system_update_tv_black_24dp.png'><br>system update tv</div>
<div><img src='./action/ic_tab_black_24dp.png'><br>tab</div>
<div><img src='./action/ic_tab_unselected_black_24dp.png'><br>tab unselected</div>
<div><img src='./action/ic_theaters_black_24dp.png'><br>theaters</div>
<div><img src='./action/ic_thumb_down_black_24dp.png'><br>thumb down</div>
<div><img src='./action/ic_thumb_up_black_24dp.png'><br>thumb up</div>
<div><img src='./action/ic_thumbs_up_down_black_24dp.png'><br>thumbs up down</div>
<div><img src='./action/ic_toc_black_24dp.png'><br>toc</div>
<div><img src='./action/ic_today_black_24dp.png'><br>today</div>
<div><img src='./action/ic_track_changes_black_24dp.png'><br>track changes</div>
<div><img src='./action/ic_translate_black_24dp.png'><br>translate</div>
<div><img src='./action/ic_trending_down_black_24dp.png'><br>trending down</div>
<div><img src='./action/ic_trending_neutral_black_24dp.png'><br>trending neutral</div>
<div><img src='./action/ic_trending_up_black_24dp.png'><br>trending up</div>
<div><img src='./action/ic_turned_in_black_24dp.png'><br>turned in</div>
<div><img src='./action/ic_turned_in_not_black_24dp.png'><br>turned in not</div>
<div><img src='./action/ic_verified_user_black_24dp.png'><br>verified user</div>
<div><img src='./action/ic_view_agenda_black_24dp.png'><br>view agenda</div>
<div><img src='./action/ic_view_array_black_24dp.png'><br>view array</div>
<div><img src='./action/ic_view_carousel_black_24dp.png'><br>view carousel</div>
<div><img src='./action/ic_view_column_black_24dp.png'><br>view column</div>
<div><img src='./action/ic_view_day_black_24dp.png'><br>view day</div>
<div><img src='./action/ic_view_headline_black_24dp.png'><br>view headline</div>
<div><img src='./action/ic_view_list_black_24dp.png'><br>view list</div>
<div><img src='./action/ic_view_module_black_24dp.png'><br>view module</div>
<div><img src='./action/ic_view_quilt_black_24dp.png'><br>view quilt</div>
<div><img src='./action/ic_view_stream_black_24dp.png'><br>view stream</div>
<div><img src='./action/ic_view_week_black_24dp.png'><br>view week</div>
<div><img src='./action/ic_visibility_black_24dp.png'><br>visibility</div>
<div><img src='./action/ic_visibility_off_black_24dp.png'><br>visibility off</div>
<div><img src='./action/ic_wallet_giftcard_black_24dp.png'><br>wallet giftcard</div>
<div><img src='./action/ic_wallet_membership_black_24dp.png'><br>wallet membership</div>
<div><img src='./action/ic_wallet_travel_black_24dp.png'><br>wallet travel</div>
<div><img src='./action/ic_work_black_24dp.png'><br>work</div>
<h1>alert</h1>
<div><img src='./alert/ic_error_black_24dp.png'><br>error</div>
<div><img src='./alert/ic_warning_black_24dp.png'><br>warning</div>
<h1>av</h1>
<div><img src='./av/ic_album_black_24dp.png'><br>album</div>
<div><img src='./av/ic_av_timer_black_24dp.png'><br>av timer</div>
<div><img src='./av/ic_closed_caption_black_24dp.png'><br>closed caption</div>
<div><img src='./av/ic_equalizer_black_24dp.png'><br>equalizer</div>
<div><img src='./av/ic_explicit_black_24dp.png'><br>explicit</div>
<div><img src='./av/ic_fast_forward_black_24dp.png'><br>fast forward</div>
<div><img src='./av/ic_fast_rewind_black_24dp.png'><br>fast rewind</div>
<div><img src='./av/ic_games_black_24dp.png'><br>games</div>
<div><img src='./av/ic_hearing_black_24dp.png'><br>hearing</div>
<div><img src='./av/ic_high_quality_black_24dp.png'><br>high quality</div>
<div><img src='./av/ic_loop_black_24dp.png'><br>loop</div>
<div><img src='./av/ic_mic_black_24dp.png'><br>mic</div>
<div><img src='./av/ic_mic_none_black_24dp.png'><br>mic none</div>
<div><img src='./av/ic_mic_off_black_24dp.png'><br>mic off</div>
<div><img src='./av/ic_movie_black_24dp.png'><br>movie</div>
<div><img src='./av/ic_my_library_add_black_24dp.png'><br>my library add</div>
<div><img src='./av/ic_my_library_books_black_24dp.png'><br>my library books</div>
<div><img src='./av/ic_my_library_music_black_24dp.png'><br>my library music</div>
<div><img src='./av/ic_new_releases_black_24dp.png'><br>new releases</div>
<div><img src='./av/ic_not_interested_black_24dp.png'><br>not interested</div>
<div><img src='./av/ic_pause_black_24dp.png'><br>pause</div>
<div><img src='./av/ic_pause_circle_fill_black_24dp.png'><br>pause circle fill</div>
<div><img src='./av/ic_pause_circle_outline_black_24dp.png'><br>pause circle outline</div>
<div><img src='./av/ic_play_arrow_black_24dp.png'><br>play arrow</div>
<div><img src='./av/ic_play_circle_fill_black_24dp.png'><br>play circle fill</div>
<div><img src='./av/ic_play_circle_outline_black_24dp.png'><br>play circle outline</div>
<div><img src='./av/ic_play_shopping_bag_black_24dp.png'><br>play shopping bag</div>
<div><img src='./av/ic_playlist_add_black_24dp.png'><br>playlist add</div>
<div><img src='./av/ic_queue_black_24dp.png'><br>queue</div>
<div><img src='./av/ic_queue_music_black_24dp.png'><br>queue music</div>
<div><img src='./av/ic_radio_black_24dp.png'><br>radio</div>
<div><img src='./av/ic_recent_actors_black_24dp.png'><br>recent actors</div>
<div><img src='./av/ic_repeat_black_24dp.png'><br>repeat</div>
<div><img src='./av/ic_repeat_one_black_24dp.png'><br>repeat one</div>
<div><img src='./av/ic_replay_black_24dp.png'><br>replay</div>
<div><img src='./av/ic_shuffle_black_24dp.png'><br>shuffle</div>
<div><img src='./av/ic_skip_next_black_24dp.png'><br>skip next</div>
<div><img src='./av/ic_skip_previous_black_24dp.png'><br>skip previous</div>
<div><img src='./av/ic_snooze_black_24dp.png'><br>snooze</div>
<div><img src='./av/ic_stop_black_24dp.png'><br>stop</div>
<div><img src='./av/ic_subtitles_black_24dp.png'><br>subtitles</div>
<div><img src='./av/ic_surround_sound_black_24dp.png'><br>surround sound</div>
<div><img src='./av/ic_video_collection_black_24dp.png'><br>video collection</div>
<div><img src='./av/ic_videocam_black_24dp.png'><br>videocam</div>
<div><img src='./av/ic_videocam_off_black_24dp.png'><br>videocam off</div>
<div><img src='./av/ic_volume_down_black_24dp.png'><br>volume down</div>
<div><img src='./av/ic_volume_mute_black_24dp.png'><br>volume mute</div>
<div><img src='./av/ic_volume_off_black_24dp.png'><br>volume off</div>
<div><img src='./av/ic_volume_up_black_24dp.png'><br>volume up</div>
<div><img src='./av/ic_web_black_24dp.png'><br>web</div>
<h1>communication</h1>
<div><img src='./communication/ic_business_black_24dp.png'><br>business</div>
<div><img src='./communication/ic_call_black_24dp.png'><br>call</div>
<div><img src='./communication/ic_call_end_black_24dp.png'><br>call end</div>
<div><img src='./communication/ic_call_made_black_24dp.png'><br>call made</div>
<div><img src='./communication/ic_call_merge_black_24dp.png'><br>call merge</div>
<div><img src='./communication/ic_call_missed_black_24dp.png'><br>call missed</div>
<div><img src='./communication/ic_call_received_black_24dp.png'><br>call received</div>
<div><img src='./communication/ic_call_split_black_24dp.png'><br>call split</div>
<div><img src='./communication/ic_chat_black_24dp.png'><br>chat</div>
<div><img src='./communication/ic_clear_all_black_24dp.png'><br>clear all</div>
<div><img src='./communication/ic_comment_black_24dp.png'><br>comment</div>
<div><img src='./communication/ic_contacts_black_24dp.png'><br>contacts</div>
<div><img src='./communication/ic_dialer_sip_black_24dp.png'><br>dialer sip</div>
<div><img src='./communication/ic_dialpad_black_24dp.png'><br>dialpad</div>
<div><img src='./communication/ic_dnd_on_black_24dp.png'><br>dnd on</div>
<div><img src='./communication/ic_email_black_24dp.png'><br>email</div>
<div><img src='./communication/ic_forum_black_24dp.png'><br>forum</div>
<div><img src='./communication/ic_import_export_black_24dp.png'><br>import export</div>
<div><img src='./communication/ic_invert_colors_off_black_24dp.png'><br>invert colors off</div>
<div><img src='./communication/ic_invert_colors_on_black_24dp.png'><br>invert colors on</div>
<div><img src='./communication/ic_live_help_black_24dp.png'><br>live help</div>
<div><img src='./communication/ic_location_off_black_24dp.png'><br>location off</div>
<div><img src='./communication/ic_location_on_black_24dp.png'><br>location on</div>
<div><img src='./communication/ic_message_black_24dp.png'><br>message</div>
<div><img src='./communication/ic_messenger_black_24dp.png'><br>messenger</div>
<div><img src='./communication/ic_no_sim_black_24dp.png'><br>no sim</div>
<div><img src='./communication/ic_phone_black_24dp.png'><br>phone</div>
<div><img src='./communication/ic_portable_wifi_off_black_24dp.png'><br>portable wifi off</div>
<div><img src='./communication/ic_quick_contacts_dialer_black_24dp.png'><br>quick contacts dialer</div>
<div><img src='./communication/ic_quick_contacts_mail_black_24dp.png'><br>quick contacts mail</div>
<div><img src='./communication/ic_ring_volume_black_24dp.png'><br>ring volume</div>
<div><img src='./communication/ic_stay_current_landscape_black_24dp.png'><br>stay current landscape</div>
<div><img src='./communication/ic_stay_current_portrait_black_24dp.png'><br>stay current portrait</div>
<div><img src='./communication/ic_stay_primary_landscape_black_24dp.png'><br>stay primary landscape</div>
<div><img src='./communication/ic_stay_primary_portrait_black_24dp.png'><br>stay primary portrait</div>
<div><img src='./communication/ic_swap_calls_black_24dp.png'><br>swap calls</div>
<div><img src='./communication/ic_textsms_black_24dp.png'><br>textsms</div>
<div><img src='./communication/ic_voicemail_black_24dp.png'><br>voicemail</div>
<div><img src='./communication/ic_vpn_key_black_24dp.png'><br>vpn key</div>
<h1>content</h1>
<div><img src='./content/ic_add_black_24dp.png'><br>add</div>
<div><img src='./content/ic_add_box_black_24dp.png'><br>add box</div>
<div><img src='./content/ic_add_circle_black_24dp.png'><br>add circle</div>
<div><img src='./content/ic_add_circle_outline_black_24dp.png'><br>add circle outline</div>
<div><img src='./content/ic_archive_black_24dp.png'><br>archive</div>
<div><img src='./content/ic_backspace_black_24dp.png'><br>backspace</div>
<div><img src='./content/ic_block_black_24dp.png'><br>block</div>
<div><img src='./content/ic_clear_black_24dp.png'><br>clear</div>
<div><img src='./content/ic_content_copy_black_24dp.png'><br>content copy</div>
<div><img src='./content/ic_content_cut_black_24dp.png'><br>content cut</div>
<div><img src='./content/ic_content_paste_black_24dp.png'><br>content paste</div>
<div><img src='./content/ic_create_black_24dp.png'><br>create</div>
<div><img src='./content/ic_drafts_black_24dp.png'><br>drafts</div>
<div><img src='./content/ic_filter_list_black_24dp.png'><br>filter list</div>
<div><img src='./content/ic_flag_black_24dp.png'><br>flag</div>
<div><img src='./content/ic_forward_black_24dp.png'><br>forward</div>
<div><img src='./content/ic_gesture_black_24dp.png'><br>gesture</div>
<div><img src='./content/ic_inbox_black_24dp.png'><br>inbox</div>
<div><img src='./content/ic_link_black_24dp.png'><br>link</div>
<div><img src='./content/ic_mail_black_24dp.png'><br>mail</div>
<div><img src='./content/ic_markunread_black_24dp.png'><br>markunread</div>
<div><img src='./content/ic_redo_black_24dp.png'><br>redo</div>
<div><img src='./content/ic_remove_black_24dp.png'><br>remove</div>
<div><img src='./content/ic_remove_circle_black_24dp.png'><br>remove circle</div>
<div><img src='./content/ic_remove_circle_outline_black_24dp.png'><br>remove circle outline</div>
<div><img src='./content/ic_reply_black_24dp.png'><br>reply</div>
<div><img src='./content/ic_reply_all_black_24dp.png'><br>reply all</div>
<div><img src='./content/ic_report_black_24dp.png'><br>report</div>
<div><img src='./content/ic_save_black_24dp.png'><br>save</div>
<div><img src='./content/ic_select_all_black_24dp.png'><br>select all</div>
<div><img src='./content/ic_send_black_24dp.png'><br>send</div>
<div><img src='./content/ic_sort_black_24dp.png'><br>sort</div>
<div><img src='./content/ic_text_format_black_24dp.png'><br>text format</div>
<div><img src='./content/ic_undo_black_24dp.png'><br>undo</div>
<h1>device</h1>
<div><img src='./device/ic_access_alarm_black_24dp.png'><br>access alarm</div>
<div><img src='./device/ic_access_alarms_black_24dp.png'><br>access alarms</div>
<div><img src='./device/ic_access_time_black_24dp.png'><br>access time</div>
<div><img src='./device/ic_add_alarm_black_24dp.png'><br>add alarm</div>
<div><img src='./device/ic_airplanemode_off_black_24dp.png'><br>airplanemode off</div>
<div><img src='./device/ic_airplanemode_on_black_24dp.png'><br>airplanemode on</div>
<div><img src='./device/ic_battery_20_black_24dp.png'><br>battery 20</div>
<div><img src='./device/ic_battery_30_black_24dp.png'><br>battery 30</div>
<div><img src='./device/ic_battery_50_black_24dp.png'><br>battery 50</div>
<div><img src='./device/ic_battery_60_black_24dp.png'><br>battery 60</div>
<div><img src='./device/ic_battery_80_black_24dp.png'><br>battery 80</div>
<div><img src='./device/ic_battery_90_black_24dp.png'><br>battery 90</div>
<div><img src='./device/ic_battery_alert_black_24dp.png'><br>battery alert</div>
<div><img src='./device/ic_battery_charging_20_black_24dp.png'><br>battery charging 20</div>
<div><img src='./device/ic_battery_charging_30_black_24dp.png'><br>battery charging 30</div>
<div><img src='./device/ic_battery_charging_50_black_24dp.png'><br>battery charging 50</div>
<div><img src='./device/ic_battery_charging_60_black_24dp.png'><br>battery charging 60</div>
<div><img src='./device/ic_battery_charging_80_black_24dp.png'><br>battery charging 80</div>
<div><img src='./device/ic_battery_charging_90_black_24dp.png'><br>battery charging 90</div>
<div><img src='./device/ic_battery_charging_full_black_24dp.png'><br>battery charging full</div>
<div><img src='./device/ic_battery_full_black_24dp.png'><br>battery full</div>
<div><img src='./device/ic_battery_std_black_24dp.png'><br>battery std</div>
<div><img src='./device/ic_battery_unknown_black_24dp.png'><br>battery unknown</div>
<div><img src='./device/ic_bluetooth_black_24dp.png'><br>bluetooth</div>
<div><img src='./device/ic_bluetooth_connected_black_24dp.png'><br>bluetooth connected</div>
<div><img src='./device/ic_bluetooth_disabled_black_24dp.png'><br>bluetooth disabled</div>
<div><img src='./device/ic_bluetooth_searching_black_24dp.png'><br>bluetooth searching</div>
<div><img src='./device/ic_brightness_auto_black_24dp.png'><br>brightness auto</div>
<div><img src='./device/ic_brightness_high_black_24dp.png'><br>brightness high</div>
<div><img src='./device/ic_brightness_low_black_24dp.png'><br>brightness low</div>
<div><img src='./device/ic_brightness_medium_black_24dp.png'><br>brightness medium</div>
<div><img src='./device/ic_data_usage_black_24dp.png'><br>data usage</div>
<div><img src='./device/ic_developer_mode_black_24dp.png'><br>developer mode</div>
<div><img src='./device/ic_devices_black_24dp.png'><br>devices</div>
<div><img src='./device/ic_dvr_black_24dp.png'><br>dvr</div>
<div><img src='./device/ic_gps_fixed_black_24dp.png'><br>gps fixed</div>
<div><img src='./device/ic_gps_not_fixed_black_24dp.png'><br>gps not fixed</div>
<div><img src='./device/ic_gps_off_black_24dp.png'><br>gps off</div>
<div><img src='./device/ic_location_disabled_black_24dp.png'><br>location disabled</div>
<div><img src='./device/ic_location_searching_black_24dp.png'><br>location searching</div>
<div><img src='./device/ic_multitrack_audio_black_24dp.png'><br>multitrack audio</div>
<div><img src='./device/ic_network_cell_black_24dp.png'><br>network cell</div>
<div><img src='./device/ic_network_wifi_black_24dp.png'><br>network wifi</div>
<div><img src='./device/ic_nfc_black_24dp.png'><br>nfc</div>
<div><img src='./device/ic_now_wallpaper_black_24dp.png'><br>now wallpaper</div>
<div><img src='./device/ic_now_widgets_black_24dp.png'><br>now widgets</div>
<div><img src='./device/ic_screen_lock_landscape_black_24dp.png'><br>screen lock landscape</div>
<div><img src='./device/ic_screen_lock_portrait_black_24dp.png'><br>screen lock portrait</div>
<div><img src='./device/ic_screen_lock_rotation_black_24dp.png'><br>screen lock rotation</div>
<div><img src='./device/ic_screen_rotation_black_24dp.png'><br>screen rotation</div>
<div><img src='./device/ic_sd_storage_black_24dp.png'><br>sd storage</div>
<div><img src='./device/ic_settings_system_daydream_black_24dp.png'><br>settings system daydream</div>
<div><img src='./device/ic_signal_cellular_0_bar_black_24dp.png'><br>signal cellular 0 bar</div>
<div><img src='./device/ic_signal_cellular_1_bar_black_24dp.png'><br>signal cellular 1 bar</div>
<div><img src='./device/ic_signal_cellular_2_bar_black_24dp.png'><br>signal cellular 2 bar</div>
<div><img src='./device/ic_signal_cellular_3_bar_black_24dp.png'><br>signal cellular 3 bar</div>
<div><img src='./device/ic_signal_cellular_4_bar_black_24dp.png'><br>signal cellular 4 bar</div>
<div><img src='./device/ic_signal_cellular_connected_no_internet_0_bar_black_24dp.png'><br>signal cellular connected no internet 0 bar</div>
<div><img src='./device/ic_signal_cellular_connected_no_internet_1_bar_black_24dp.png'><br>signal cellular connected no internet 1 bar</div>
<div><img src='./device/ic_signal_cellular_connected_no_internet_2_bar_black_24dp.png'><br>signal cellular connected no internet 2 bar</div>
<div><img src='./device/ic_signal_cellular_connected_no_internet_3_bar_black_24dp.png'><br>signal cellular connected no internet 3 bar</div>
<div><img src='./device/ic_signal_cellular_connected_no_internet_4_bar_black_24dp.png'><br>signal cellular connected no internet 4 bar</div>
<div><img src='./device/ic_signal_cellular_no_sim_black_24dp.png'><br>signal cellular no sim</div>
<div><img src='./device/ic_signal_cellular_null_black_24dp.png'><br>signal cellular null</div>
<div><img src='./device/ic_signal_cellular_off_black_24dp.png'><br>signal cellular off</div>
<div><img src='./device/ic_signal_wifi_0_bar_black_24dp.png'><br>signal wifi 0 bar</div>
<div><img src='./device/ic_signal_wifi_1_bar_black_24dp.png'><br>signal wifi 1 bar</div>
<div><img src='./device/ic_signal_wifi_2_bar_black_24dp.png'><br>signal wifi 2 bar</div>
<div><img src='./device/ic_signal_wifi_3_bar_black_24dp.png'><br>signal wifi 3 bar</div>
<div><img src='./device/ic_signal_wifi_4_bar_black_24dp.png'><br>signal wifi 4 bar</div>
<div><img src='./device/ic_signal_wifi_off_black_24dp.png'><br>signal wifi off</div>
<div><img src='./device/ic_signal_wifi_statusbar_1_bar_26x24dp.png'><br>signal wifi statusbar 1 bar</div>
<div><img src='./device/ic_signal_wifi_statusbar_2_bar_26x24dp.png'><br>signal wifi statusbar 2 bar</div>
<div><img src='./device/ic_signal_wifi_statusbar_3_bar_26x24dp.png'><br>signal wifi statusbar 3 bar</div>
<div><img src='./device/ic_signal_wifi_statusbar_4_bar_26x24dp.png'><br>signal wifi statusbar 4 bar</div>
<div><img src='./device/ic_signal_wifi_statusbar_connected_no_internet_1_26x24dp.png'><br>signal wifi statusbar connected no internet 1</div>
<div><img src='./device/ic_signal_wifi_statusbar_connected_no_internet_26x24dp.png'><br>signal wifi statusbar connected no internet</div>
<div><img src='./device/ic_signal_wifi_statusbar_connected_no_internet_2_26x24dp.png'><br>signal wifi statusbar connected no internet 2</div>
<div><img src='./device/ic_signal_wifi_statusbar_connected_no_internet_3_26x24dp.png'><br>signal wifi statusbar connected no internet 3</div>
<div><img src='./device/ic_signal_wifi_statusbar_connected_no_internet_4_26x24dp.png'><br>signal wifi statusbar connected no internet 4</div>
<div><img src='./device/ic_signal_wifi_statusbar_not_connected_26x24dp.png'><br>signal wifi statusbar not connected</div>
<div><img src='./device/ic_signal_wifi_statusbar_null_26x24dp.png'><br>signal wifi statusbar null</div>
<div><img src='./device/ic_storage_black_24dp.png'><br>storage</div>
<div><img src='./device/ic_usb_black_24dp.png'><br>usb</div>
<div><img src='./device/ic_wifi_lock_black_24dp.png'><br>wifi lock</div>
<div><img src='./device/ic_wifi_tethering_black_24dp.png'><br>wifi tethering</div>
<h1>editor</h1>
<div><img src='./editor/ic_attach_file_black_24dp.png'><br>attach file</div>
<div><img src='./editor/ic_attach_money_black_24dp.png'><br>attach money</div>
<div><img src='./editor/ic_border_all_black_24dp.png'><br>border all</div>
<div><img src='./editor/ic_border_bottom_black_24dp.png'><br>border bottom</div>
<div><img src='./editor/ic_border_clear_black_24dp.png'><br>border clear</div>
<div><img src='./editor/ic_border_color_black_24dp.png'><br>border color</div>
<div><img src='./editor/ic_border_horizontal_black_24dp.png'><br>border horizontal</div>
<div><img src='./editor/ic_border_inner_black_24dp.png'><br>border inner</div>
<div><img src='./editor/ic_border_left_black_24dp.png'><br>border left</div>
<div><img src='./editor/ic_border_outer_black_24dp.png'><br>border outer</div>
<div><img src='./editor/ic_border_right_black_24dp.png'><br>border right</div>
<div><img src='./editor/ic_border_style_black_24dp.png'><br>border style</div>
<div><img src='./editor/ic_border_top_black_24dp.png'><br>border top</div>
<div><img src='./editor/ic_border_vertical_black_24dp.png'><br>border vertical</div>
<div><img src='./editor/ic_format_align_center_black_24dp.png'><br>format align center</div>
<div><img src='./editor/ic_format_align_justify_black_24dp.png'><br>format align justify</div>
<div><img src='./editor/ic_format_align_left_black_24dp.png'><br>format align left</div>
<div><img src='./editor/ic_format_align_right_black_24dp.png'><br>format align right</div>
<div><img src='./editor/ic_format_bold_black_24dp.png'><br>format bold</div>
<div><img src='./editor/ic_format_clear_black_24dp.png'><br>format clear</div>
<div><img src='./editor/ic_format_color_fill_black_24dp.png'><br>format color fill</div>
<div><img src='./editor/ic_format_color_reset_black_24dp.png'><br>format color reset</div>
<div><img src='./editor/ic_format_color_text_black_24dp.png'><br>format color text</div>
<div><img src='./editor/ic_format_indent_decrease_black_24dp.png'><br>format indent decrease</div>
<div><img src='./editor/ic_format_indent_increase_black_24dp.png'><br>format indent increase</div>
<div><img src='./editor/ic_format_italic_black_24dp.png'><br>format italic</div>
<div><img src='./editor/ic_format_line_spacing_black_24dp.png'><br>format line spacing</div>
<div><img src='./editor/ic_format_list_bulleted_black_24dp.png'><br>format list bulleted</div>
<div><img src='./editor/ic_format_list_numbered_black_24dp.png'><br>format list numbered</div>
<div><img src='./editor/ic_format_paint_black_24dp.png'><br>format paint</div>
<div><img src='./editor/ic_format_quote_black_24dp.png'><br>format quote</div>
<div><img src='./editor/ic_format_size_black_24dp.png'><br>format size</div>
<div><img src='./editor/ic_format_strikethrough_black_24dp.png'><br>format strikethrough</div>
<div><img src='./editor/ic_format_textdirection_l_to_r_black_24dp.png'><br>format textdirection l to r</div>
<div><img src='./editor/ic_format_textdirection_r_to_l_black_24dp.png'><br>format textdirection r to l</div>
<div><img src='./editor/ic_format_underline_black_24dp.png'><br>format underline</div>
<div><img src='./editor/ic_functions_black_24dp.png'><br>functions</div>
<div><img src='./editor/ic_insert_chart_black_24dp.png'><br>insert chart</div>
<div><img src='./editor/ic_insert_comment_black_24dp.png'><br>insert comment</div>
<div><img src='./editor/ic_insert_drive_file_black_24dp.png'><br>insert drive file</div>
<div><img src='./editor/ic_insert_emoticon_black_24dp.png'><br>insert emoticon</div>
<div><img src='./editor/ic_insert_invitation_black_24dp.png'><br>insert invitation</div>
<div><img src='./editor/ic_insert_link_black_24dp.png'><br>insert link</div>
<div><img src='./editor/ic_insert_photo_black_24dp.png'><br>insert photo</div>
<div><img src='./editor/ic_merge_type_black_24dp.png'><br>merge type</div>
<div><img src='./editor/ic_mode_comment_black_24dp.png'><br>mode comment</div>
<div><img src='./editor/ic_mode_edit_black_24dp.png'><br>mode edit</div>
<div><img src='./editor/ic_publish_black_24dp.png'><br>publish</div>
<div><img src='./editor/ic_vertical_align_bottom_black_24dp.png'><br>vertical align bottom</div>
<div><img src='./editor/ic_vertical_align_center_black_24dp.png'><br>vertical align center</div>
<div><img src='./editor/ic_vertical_align_top_black_24dp.png'><br>vertical align top</div>
<div><img src='./editor/ic_wrap_text_black_24dp.png'><br>wrap text</div>
<h1>file</h1>
<div><img src='./file/ic_attachment_black_24dp.png'><br>attachment</div>
<div><img src='./file/ic_cloud_black_24dp.png'><br>cloud</div>
<div><img src='./file/ic_cloud_circle_black_24dp.png'><br>cloud circle</div>
<div><img src='./file/ic_cloud_done_black_24dp.png'><br>cloud done</div>
<div><img src='./file/ic_cloud_download_black_24dp.png'><br>cloud download</div>
<div><img src='./file/ic_cloud_off_black_24dp.png'><br>cloud off</div>
<div><img src='./file/ic_cloud_queue_black_24dp.png'><br>cloud queue</div>
<div><img src='./file/ic_cloud_upload_black_24dp.png'><br>cloud upload</div>
<div><img src='./file/ic_file_download_black_24dp.png'><br>file download</div>
<div><img src='./file/ic_file_upload_black_24dp.png'><br>file upload</div>
<div><img src='./file/ic_folder_black_24dp.png'><br>folder</div>
<div><img src='./file/ic_folder_open_black_24dp.png'><br>folder open</div>
<div><img src='./file/ic_folder_shared_black_24dp.png'><br>folder shared</div>
<h1>hardware</h1>
<div><img src='./hardware/ic_cast_black_24dp.png'><br>cast</div>
<div><img src='./hardware/ic_cast_connected_black_24dp.png'><br>cast connected</div>
<div><img src='./hardware/ic_computer_black_24dp.png'><br>computer</div>
<div><img src='./hardware/ic_desktop_mac_black_24dp.png'><br>desktop mac</div>
<div><img src='./hardware/ic_desktop_windows_black_24dp.png'><br>desktop windows</div>
<div><img src='./hardware/ic_dock_black_24dp.png'><br>dock</div>
<div><img src='./hardware/ic_gamepad_black_24dp.png'><br>gamepad</div>
<div><img src='./hardware/ic_headset_black_24dp.png'><br>headset</div>
<div><img src='./hardware/ic_headset_mic_black_24dp.png'><br>headset mic</div>
<div><img src='./hardware/ic_keyboard_black_24dp.png'><br>keyboard</div>
<div><img src='./hardware/ic_keyboard_alt_black_24dp.png'><br>keyboard alt</div>
<div><img src='./hardware/ic_keyboard_arrow_down_black_24dp.png'><br>keyboard arrow down</div>
<div><img src='./hardware/ic_keyboard_arrow_left_black_24dp.png'><br>keyboard arrow left</div>
<div><img src='./hardware/ic_keyboard_arrow_right_black_24dp.png'><br>keyboard arrow right</div>
<div><img src='./hardware/ic_keyboard_arrow_up_black_24dp.png'><br>keyboard arrow up</div>
<div><img src='./hardware/ic_keyboard_backspace_black_24dp.png'><br>keyboard backspace</div>
<div><img src='./hardware/ic_keyboard_capslock_black_24dp.png'><br>keyboard capslock</div>
<div><img src='./hardware/ic_keyboard_control_black_24dp.png'><br>keyboard control</div>
<div><img src='./hardware/ic_keyboard_hide_black_24dp.png'><br>keyboard hide</div>
<div><img src='./hardware/ic_keyboard_return_black_24dp.png'><br>keyboard return</div>
<div><img src='./hardware/ic_keyboard_tab_black_24dp.png'><br>keyboard tab</div>
<div><img src='./hardware/ic_keyboard_voice_black_24dp.png'><br>keyboard voice</div>
<div><img src='./hardware/ic_laptop_black_24dp.png'><br>laptop</div>
<div><img src='./hardware/ic_laptop_chromebook_black_24dp.png'><br>laptop chromebook</div>
<div><img src='./hardware/ic_laptop_mac_black_24dp.png'><br>laptop mac</div>
<div><img src='./hardware/ic_laptop_windows_black_24dp.png'><br>laptop windows</div>
<div><img src='./hardware/ic_memory_black_24dp.png'><br>memory</div>
<div><img src='./hardware/ic_mouse_black_24dp.png'><br>mouse</div>
<div><img src='./hardware/ic_phone_android_black_24dp.png'><br>phone android</div>
<div><img src='./hardware/ic_phone_iphone_black_24dp.png'><br>phone iphone</div>
<div><img src='./hardware/ic_phonelink_black_24dp.png'><br>phonelink</div>
<div><img src='./hardware/ic_phonelink_off_black_24dp.png'><br>phonelink off</div>
<div><img src='./hardware/ic_security_black_24dp.png'><br>security</div>
<div><img src='./hardware/ic_sim_card_black_24dp.png'><br>sim card</div>
<div><img src='./hardware/ic_smartphone_black_24dp.png'><br>smartphone</div>
<div><img src='./hardware/ic_speaker_black_24dp.png'><br>speaker</div>
<div><img src='./hardware/ic_tablet_black_24dp.png'><br>tablet</div>
<div><img src='./hardware/ic_tablet_android_black_24dp.png'><br>tablet android</div>
<div><img src='./hardware/ic_tablet_mac_black_24dp.png'><br>tablet mac</div>
<div><img src='./hardware/ic_tv_black_24dp.png'><br>tv</div>
<div><img src='./hardware/ic_watch_black_24dp.png'><br>watch</div>
<h1>image</h1>
<div><img src='./image/ic_add_to_photos_black_24dp.png'><br>add to photos</div>
<div><img src='./image/ic_adjust_black_24dp.png'><br>adjust</div>
<div><img src='./image/ic_assistant_photo_black_24dp.png'><br>assistant photo</div>
<div><img src='./image/ic_audiotrack_black_24dp.png'><br>audiotrack</div>
<div><img src='./image/ic_blur_circular_black_24dp.png'><br>blur circular</div>
<div><img src='./image/ic_blur_linear_black_24dp.png'><br>blur linear</div>
<div><img src='./image/ic_blur_off_black_24dp.png'><br>blur off</div>
<div><img src='./image/ic_blur_on_black_24dp.png'><br>blur on</div>
<div><img src='./image/ic_brightness_1_black_24dp.png'><br>brightness 1</div>
<div><img src='./image/ic_brightness_2_black_24dp.png'><br>brightness 2</div>
<div><img src='./image/ic_brightness_3_black_24dp.png'><br>brightness 3</div>
<div><img src='./image/ic_brightness_4_black_24dp.png'><br>brightness 4</div>
<div><img src='./image/ic_brightness_5_black_24dp.png'><br>brightness 5</div>
<div><img src='./image/ic_brightness_6_black_24dp.png'><br>brightness 6</div>
<div><img src='./image/ic_brightness_7_black_24dp.png'><br>brightness 7</div>
<div><img src='./image/ic_brush_black_24dp.png'><br>brush</div>
<div><img src='./image/ic_camera_black_24dp.png'><br>camera</div>
<div><img src='./image/ic_camera_alt_black_24dp.png'><br>camera alt</div>
<div><img src='./image/ic_camera_front_black_24dp.png'><br>camera front</div>
<div><img src='./image/ic_camera_rear_black_24dp.png'><br>camera rear</div>
<div><img src='./image/ic_camera_roll_black_24dp.png'><br>camera roll</div>
<div><img src='./image/ic_center_focus_strong_black_24dp.png'><br>center focus strong</div>
<div><img src='./image/ic_center_focus_weak_black_24dp.png'><br>center focus weak</div>
<div><img src='./image/ic_collections_black_24dp.png'><br>collections</div>
<div><img src='./image/ic_color_lens_black_24dp.png'><br>color lens</div>
<div><img src='./image/ic_colorize_black_24dp.png'><br>colorize</div>
<div><img src='./image/ic_compare_black_24dp.png'><br>compare</div>
<div><img src='./image/ic_control_point_black_24dp.png'><br>control point</div>
<div><img src='./image/ic_control_point_duplicate_black_24dp.png'><br>control point duplicate</div>
<div><img src='./image/ic_crop_16_9_black_24dp.png'><br>crop 16 9</div>
<div><img src='./image/ic_crop_black_24dp.png'><br>crop</div>
<div><img src='./image/ic_crop_3_2_black_24dp.png'><br>crop 3 2</div>
<div><img src='./image/ic_crop_5_4_black_24dp.png'><br>crop 5 4</div>
<div><img src='./image/ic_crop_7_5_black_24dp.png'><br>crop 7 5</div>
<div><img src='./image/ic_crop_din_black_24dp.png'><br>crop din</div>
<div><img src='./image/ic_crop_free_black_24dp.png'><br>crop free</div>
<div><img src='./image/ic_crop_landscape_black_24dp.png'><br>crop landscape</div>
<div><img src='./image/ic_crop_original_black_24dp.png'><br>crop original</div>
<div><img src='./image/ic_crop_portrait_black_24dp.png'><br>crop portrait</div>
<div><img src='./image/ic_crop_square_black_24dp.png'><br>crop square</div>
<div><img src='./image/ic_dehaze_black_24dp.png'><br>dehaze</div>
<div><img src='./image/ic_details_black_24dp.png'><br>details</div>
<div><img src='./image/ic_edit_black_24dp.png'><br>edit</div>
<div><img src='./image/ic_exposure_black_24dp.png'><br>exposure</div>
<div><img src='./image/ic_exposure_minus_1_black_24dp.png'><br>exposure minus 1</div>
<div><img src='./image/ic_exposure_minus_2_black_24dp.png'><br>exposure minus 2</div>
<div><img src='./image/ic_exposure_plus_1_black_24dp.png'><br>exposure plus 1</div>
<div><img src='./image/ic_exposure_plus_2_black_24dp.png'><br>exposure plus 2</div>
<div><img src='./image/ic_exposure_zero_black_24dp.png'><br>exposure zero</div>
<div><img src='./image/ic_filter_1_black_24dp.png'><br>filter 1</div>
<div><img src='./image/ic_filter_black_24dp.png'><br>filter</div>
<div><img src='./image/ic_filter_2_black_24dp.png'><br>filter 2</div>
<div><img src='./image/ic_filter_3_black_24dp.png'><br>filter 3</div>
<div><img src='./image/ic_filter_4_black_24dp.png'><br>filter 4</div>
<div><img src='./image/ic_filter_5_black_24dp.png'><br>filter 5</div>
<div><img src='./image/ic_filter_6_black_24dp.png'><br>filter 6</div>
<div><img src='./image/ic_filter_7_black_24dp.png'><br>filter 7</div>
<div><img src='./image/ic_filter_8_black_24dp.png'><br>filter 8</div>
<div><img src='./image/ic_filter_9_black_24dp.png'><br>filter 9</div>
<div><img src='./image/ic_filter_9_plus_black_24dp.png'><br>filter 9 plus</div>
<div><img src='./image/ic_filter_b_and_w_black_24dp.png'><br>filter b and w</div>
<div><img src='./image/ic_filter_center_focus_black_24dp.png'><br>filter center focus</div>
<div><img src='./image/ic_filter_drama_black_24dp.png'><br>filter drama</div>
<div><img src='./image/ic_filter_frames_black_24dp.png'><br>filter frames</div>
<div><img src='./image/ic_filter_hdr_black_24dp.png'><br>filter hdr</div>
<div><img src='./image/ic_filter_none_black_24dp.png'><br>filter none</div>
<div><img src='./image/ic_filter_tilt_shift_black_24dp.png'><br>filter tilt shift</div>
<div><img src='./image/ic_filter_vintage_black_24dp.png'><br>filter vintage</div>
<div><img src='./image/ic_flare_black_24dp.png'><br>flare</div>
<div><img src='./image/ic_flash_auto_black_24dp.png'><br>flash auto</div>
<div><img src='./image/ic_flash_off_black_24dp.png'><br>flash off</div>
<div><img src='./image/ic_flash_on_black_24dp.png'><br>flash on</div>
<div><img src='./image/ic_flip_black_24dp.png'><br>flip</div>
<div><img src='./image/ic_gradient_black_24dp.png'><br>gradient</div>
<div><img src='./image/ic_grain_black_24dp.png'><br>grain</div>
<div><img src='./image/ic_grid_off_black_24dp.png'><br>grid off</div>
<div><img src='./image/ic_grid_on_black_24dp.png'><br>grid on</div>
<div><img src='./image/ic_hdr_off_black_24dp.png'><br>hdr off</div>
<div><img src='./image/ic_hdr_on_black_24dp.png'><br>hdr on</div>
<div><img src='./image/ic_hdr_strong_black_24dp.png'><br>hdr strong</div>
<div><img src='./image/ic_hdr_weak_black_24dp.png'><br>hdr weak</div>
<div><img src='./image/ic_healing_black_24dp.png'><br>healing</div>
<div><img src='./image/ic_image_black_24dp.png'><br>image</div>
<div><img src='./image/ic_image_aspect_ratio_black_24dp.png'><br>image aspect ratio</div>
<div><img src='./image/ic_iso_black_24dp.png'><br>iso</div>
<div><img src='./image/ic_landscape_black_24dp.png'><br>landscape</div>
<div><img src='./image/ic_leak_add_black_24dp.png'><br>leak add</div>
<div><img src='./image/ic_leak_remove_black_24dp.png'><br>leak remove</div>
<div><img src='./image/ic_lens_black_24dp.png'><br>lens</div>
<div><img src='./image/ic_looks_black_24dp.png'><br>looks</div>
<div><img src='./image/ic_looks_3_black_24dp.png'><br>looks 3</div>
<div><img src='./image/ic_looks_4_black_24dp.png'><br>looks 4</div>
<div><img src='./image/ic_looks_5_black_24dp.png'><br>looks 5</div>
<div><img src='./image/ic_looks_6_black_24dp.png'><br>looks 6</div>
<div><img src='./image/ic_looks_one_black_24dp.png'><br>looks one</div>
<div><img src='./image/ic_looks_two_black_24dp.png'><br>looks two</div>
<div><img src='./image/ic_loupe_black_24dp.png'><br>loupe</div>
<div><img src='./image/ic_movie_creation_black_24dp.png'><br>movie creation</div>
<div><img src='./image/ic_nature_black_24dp.png'><br>nature</div>
<div><img src='./image/ic_nature_people_black_24dp.png'><br>nature people</div>
<div><img src='./image/ic_navigate_before_black_24dp.png'><br>navigate before</div>
<div><img src='./image/ic_navigate_next_black_24dp.png'><br>navigate next</div>
<div><img src='./image/ic_palette_black_24dp.png'><br>palette</div>
<div><img src='./image/ic_panorama_black_24dp.png'><br>panorama</div>
<div><img src='./image/ic_panorama_fisheye_black_24dp.png'><br>panorama fisheye</div>
<div><img src='./image/ic_panorama_horizontal_black_24dp.png'><br>panorama horizontal</div>
<div><img src='./image/ic_panorama_vertical_black_24dp.png'><br>panorama vertical</div>
<div><img src='./image/ic_panorama_wide_angle_black_24dp.png'><br>panorama wide angle</div>
<div><img src='./image/ic_photo_black_24dp.png'><br>photo</div>
<div><img src='./image/ic_photo_album_black_24dp.png'><br>photo album</div>
<div><img src='./image/ic_photo_camera_black_24dp.png'><br>photo camera</div>
<div><img src='./image/ic_photo_library_black_24dp.png'><br>photo library</div>
<div><img src='./image/ic_portrait_black_24dp.png'><br>portrait</div>
<div><img src='./image/ic_remove_red_eye_black_24dp.png'><br>remove red eye</div>
<div><img src='./image/ic_rotate_left_black_24dp.png'><br>rotate left</div>
<div><img src='./image/ic_rotate_right_black_24dp.png'><br>rotate right</div>
<div><img src='./image/ic_slideshow_black_24dp.png'><br>slideshow</div>
<div><img src='./image/ic_straighten_black_24dp.png'><br>straighten</div>
<div><img src='./image/ic_style_black_24dp.png'><br>style</div>
<div><img src='./image/ic_switch_camera_black_24dp.png'><br>switch camera</div>
<div><img src='./image/ic_switch_video_black_24dp.png'><br>switch video</div>
<div><img src='./image/ic_tag_faces_black_24dp.png'><br>tag faces</div>
<div><img src='./image/ic_texture_black_24dp.png'><br>texture</div>
<div><img src='./image/ic_timelapse_black_24dp.png'><br>timelapse</div>
<div><img src='./image/ic_timer_10_black_24dp.png'><br>timer 10</div>
<div><img src='./image/ic_timer_black_24dp.png'><br>timer</div>
<div><img src='./image/ic_timer_3_black_24dp.png'><br>timer 3</div>
<div><img src='./image/ic_timer_auto_black_24dp.png'><br>timer auto</div>
<div><img src='./image/ic_timer_off_black_24dp.png'><br>timer off</div>
<div><img src='./image/ic_tonality_black_24dp.png'><br>tonality</div>
<div><img src='./image/ic_transform_black_24dp.png'><br>transform</div>
<div><img src='./image/ic_tune_black_24dp.png'><br>tune</div>
<div><img src='./image/ic_wb_auto_black_24dp.png'><br>wb auto</div>
<div><img src='./image/ic_wb_cloudy_black_24dp.png'><br>wb cloudy</div>
<div><img src='./image/ic_wb_incandescent_black_24dp.png'><br>wb incandescent</div>
<div><img src='./image/ic_wb_irradescent_black_24dp.png'><br>wb irradescent</div>
<div><img src='./image/ic_wb_sunny_black_24dp.png'><br>wb sunny</div>
<h1>maps</h1>
<div><img src='./maps/ic_beenhere_black_24dp.png'><br>beenhere</div>
<div><img src='./maps/ic_directions_black_24dp.png'><br>directions</div>
<div><img src='./maps/ic_directions_bike_black_24dp.png'><br>directions bike</div>
<div><img src='./maps/ic_directions_bus_black_24dp.png'><br>directions bus</div>
<div><img src='./maps/ic_directions_car_black_24dp.png'><br>directions car</div>
<div><img src='./maps/ic_directions_ferry_black_24dp.png'><br>directions ferry</div>
<div><img src='./maps/ic_directions_subway_black_24dp.png'><br>directions subway</div>
<div><img src='./maps/ic_directions_train_black_24dp.png'><br>directions train</div>
<div><img src='./maps/ic_directions_transit_black_24dp.png'><br>directions transit</div>
<div><img src='./maps/ic_directions_walk_black_24dp.png'><br>directions walk</div>
<div><img src='./maps/ic_flight_black_24dp.png'><br>flight</div>
<div><img src='./maps/ic_hotel_black_24dp.png'><br>hotel</div>
<div><img src='./maps/ic_layers_black_24dp.png'><br>layers</div>
<div><img src='./maps/ic_layers_clear_black_24dp.png'><br>layers clear</div>
<div><img src='./maps/ic_local_airport_black_24dp.png'><br>local airport</div>
<div><img src='./maps/ic_local_atm_black_24dp.png'><br>local atm</div>
<div><img src='./maps/ic_local_attraction_black_24dp.png'><br>local attraction</div>
<div><img src='./maps/ic_local_bar_black_24dp.png'><br>local bar</div>
<div><img src='./maps/ic_local_cafe_black_24dp.png'><br>local cafe</div>
<div><img src='./maps/ic_local_car_wash_black_24dp.png'><br>local car wash</div>
<div><img src='./maps/ic_local_convenience_store_black_24dp.png'><br>local convenience store</div>
<div><img src='./maps/ic_local_drink_black_24dp.png'><br>local drink</div>
<div><img src='./maps/ic_local_florist_black_24dp.png'><br>local florist</div>
<div><img src='./maps/ic_local_gas_station_black_24dp.png'><br>local gas station</div>
<div><img src='./maps/ic_local_grocery_store_black_24dp.png'><br>local grocery store</div>
<div><img src='./maps/ic_local_hospital_black_24dp.png'><br>local hospital</div>
<div><img src='./maps/ic_local_hotel_black_24dp.png'><br>local hotel</div>
<div><img src='./maps/ic_local_laundry_service_black_24dp.png'><br>local laundry service</div>
<div><img src='./maps/ic_local_library_black_24dp.png'><br>local library</div>
<div><img src='./maps/ic_local_mall_black_24dp.png'><br>local mall</div>
<div><img src='./maps/ic_local_movies_black_24dp.png'><br>local movies</div>
<div><img src='./maps/ic_local_offer_black_24dp.png'><br>local offer</div>
<div><img src='./maps/ic_local_parking_black_24dp.png'><br>local parking</div>
<div><img src='./maps/ic_local_pharmacy_black_24dp.png'><br>local pharmacy</div>
<div><img src='./maps/ic_local_phone_black_24dp.png'><br>local phone</div>
<div><img src='./maps/ic_local_pizza_black_24dp.png'><br>local pizza</div>
<div><img src='./maps/ic_local_play_black_24dp.png'><br>local play</div>
<div><img src='./maps/ic_local_post_office_black_24dp.png'><br>local post office</div>
<div><img src='./maps/ic_local_print_shop_black_24dp.png'><br>local print shop</div>
<div><img src='./maps/ic_local_restaurant_black_24dp.png'><br>local restaurant</div>
<div><img src='./maps/ic_local_see_black_24dp.png'><br>local see</div>
<div><img src='./maps/ic_local_shipping_black_24dp.png'><br>local shipping</div>
<div><img src='./maps/ic_local_taxi_black_24dp.png'><br>local taxi</div>
<div><img src='./maps/ic_location_history_black_24dp.png'><br>location history</div>
<div><img src='./maps/ic_map_black_24dp.png'><br>map</div>
<div><img src='./maps/ic_my_location_black_24dp.png'><br>my location</div>
<div><img src='./maps/ic_navigation_black_24dp.png'><br>navigation</div>
<div><img src='./maps/ic_pin_drop_black_24dp.png'><br>pin drop</div>
<div><img src='./maps/ic_place_black_24dp.png'><br>place</div>
<div><img src='./maps/ic_rate_review_black_24dp.png'><br>rate review</div>
<div><img src='./maps/ic_restaurant_menu_black_24dp.png'><br>restaurant menu</div>
<div><img src='./maps/ic_satellite_black_24dp.png'><br>satellite</div>
<div><img src='./maps/ic_store_mall_directory_black_24dp.png'><br>store mall directory</div>
<div><img src='./maps/ic_terrain_black_24dp.png'><br>terrain</div>
<div><img src='./maps/ic_traffic_black_24dp.png'><br>traffic</div>
<h1>navigation</h1>
<div><img src='./navigation/ic_apps_black_24dp.png'><br>apps</div>
<div><img src='./navigation/ic_arrow_back_black_24dp.png'><br>arrow back</div>
<div><img src='./navigation/ic_arrow_drop_down_black_24dp.png'><br>arrow drop down</div>
<div><img src='./navigation/ic_arrow_drop_down_circle_black_24dp.png'><br>arrow drop down circle</div>
<div><img src='./navigation/ic_arrow_drop_up_black_24dp.png'><br>arrow drop up</div>
<div><img src='./navigation/ic_arrow_forward_black_24dp.png'><br>arrow forward</div>
<div><img src='./navigation/ic_cancel_black_24dp.png'><br>cancel</div>
<div><img src='./navigation/ic_check_black_24dp.png'><br>check</div>
<div><img src='./navigation/ic_chevron_left_black_24dp.png'><br>chevron left</div>
<div><img src='./navigation/ic_chevron_right_black_24dp.png'><br>chevron right</div>
<div><img src='./navigation/ic_close_black_24dp.png'><br>close</div>
<div><img src='./navigation/ic_expand_less_black_24dp.png'><br>expand less</div>
<div><img src='./navigation/ic_expand_more_black_24dp.png'><br>expand more</div>
<div><img src='./navigation/ic_fullscreen_black_24dp.png'><br>fullscreen</div>
<div><img src='./navigation/ic_fullscreen_exit_black_24dp.png'><br>fullscreen exit</div>
<div><img src='./navigation/ic_menu_black_24dp.png'><br>menu</div>
<div><img src='./navigation/ic_more_horiz_black_24dp.png'><br>more horiz</div>
<div><img src='./navigation/ic_more_vert_black_24dp.png'><br>more vert</div>
<div><img src='./navigation/ic_refresh_black_24dp.png'><br>refresh</div>
<div><img src='./navigation/ic_unfold_less_black_24dp.png'><br>unfold less</div>
<div><img src='./navigation/ic_unfold_more_black_24dp.png'><br>unfold more</div>
<h1>notification</h1>
<div><img src='./notification/ic_adb_black_24dp.png'><br>adb</div>
<div><img src='./notification/ic_bluetooth_audio_black_24dp.png'><br>bluetooth audio</div>
<div><img src='./notification/ic_disc_full_black_24dp.png'><br>disc full</div>
<div><img src='./notification/ic_dnd_forwardslash_black_24dp.png'><br>dnd forwardslash</div>
<div><img src='./notification/ic_do_not_disturb_black_24dp.png'><br>do not disturb</div>
<div><img src='./notification/ic_drive_eta_black_24dp.png'><br>drive eta</div>
<div><img src='./notification/ic_event_available_black_24dp.png'><br>event available</div>
<div><img src='./notification/ic_event_busy_black_24dp.png'><br>event busy</div>
<div><img src='./notification/ic_event_note_black_24dp.png'><br>event note</div>
<div><img src='./notification/ic_folder_special_black_24dp.png'><br>folder special</div>
<div><img src='./notification/ic_mms_black_24dp.png'><br>mms</div>
<div><img src='./notification/ic_more_black_24dp.png'><br>more</div>
<div><img src='./notification/ic_network_locked_black_24dp.png'><br>network locked</div>
<div><img src='./notification/ic_phone_bluetooth_speaker_black_24dp.png'><br>phone bluetooth speaker</div>
<div><img src='./notification/ic_phone_forwarded_black_24dp.png'><br>phone forwarded</div>
<div><img src='./notification/ic_phone_in_talk_black_24dp.png'><br>phone in talk</div>
<div><img src='./notification/ic_phone_locked_black_24dp.png'><br>phone locked</div>
<div><img src='./notification/ic_phone_missed_black_24dp.png'><br>phone missed</div>
<div><img src='./notification/ic_phone_paused_black_24dp.png'><br>phone paused</div>
<div><img src='./notification/ic_play_download_black_24dp.png'><br>play download</div>
<div><img src='./notification/ic_play_install_black_24dp.png'><br>play install</div>
<div><img src='./notification/ic_sd_card_black_24dp.png'><br>sd card</div>
<div><img src='./notification/ic_sim_card_alert_black_24dp.png'><br>sim card alert</div>
<div><img src='./notification/ic_sms_black_24dp.png'><br>sms</div>
<div><img src='./notification/ic_sms_failed_black_24dp.png'><br>sms failed</div>
<div><img src='./notification/ic_sync_black_24dp.png'><br>sync</div>
<div><img src='./notification/ic_sync_disabled_black_24dp.png'><br>sync disabled</div>
<div><img src='./notification/ic_sync_problem_black_24dp.png'><br>sync problem</div>
<div><img src='./notification/ic_system_update_black_24dp.png'><br>system update</div>
<div><img src='./notification/ic_tap_and_play_black_24dp.png'><br>tap and play</div>
<div><img src='./notification/ic_time_to_leave_black_24dp.png'><br>time to leave</div>
<div><img src='./notification/ic_vibration_black_24dp.png'><br>vibration</div>
<div><img src='./notification/ic_voice_chat_black_24dp.png'><br>voice chat</div>
<div><img src='./notification/ic_vpn_lock_black_24dp.png'><br>vpn lock</div>
<h1>social</h1>
<div><img src='./social/ic_cake_black_24dp.png'><br>cake</div>
<div><img src='./social/ic_domain_black_24dp.png'><br>domain</div>
<div><img src='./social/ic_group_black_24dp.png'><br>group</div>
<div><img src='./social/ic_group_add_black_24dp.png'><br>group add</div>
<div><img src='./social/ic_location_city_black_24dp.png'><br>location city</div>
<div><img src='./social/ic_mood_black_24dp.png'><br>mood</div>
<div><img src='./social/ic_notifications_black_24dp.png'><br>notifications</div>
<div><img src='./social/ic_notifications_none_black_24dp.png'><br>notifications none</div>
<div><img src='./social/ic_notifications_off_black_24dp.png'><br>notifications off</div>
<div><img src='./social/ic_notifications_on_black_24dp.png'><br>notifications on</div>
<div><img src='./social/ic_notifications_paused_black_24dp.png'><br>notifications paused</div>
<div><img src='./social/ic_pages_black_24dp.png'><br>pages</div>
<div><img src='./social/ic_party_mode_black_24dp.png'><br>party mode</div>
<div><img src='./social/ic_people_black_24dp.png'><br>people</div>
<div><img src='./social/ic_people_outline_black_24dp.png'><br>people outline</div>
<div><img src='./social/ic_person_black_24dp.png'><br>person</div>
<div><img src='./social/ic_person_add_black_24dp.png'><br>person add</div>
<div><img src='./social/ic_person_outline_black_24dp.png'><br>person outline</div>
<div><img src='./social/ic_plus_one_black_24dp.png'><br>plus one</div>
<div><img src='./social/ic_poll_black_24dp.png'><br>poll</div>
<div><img src='./social/ic_public_black_24dp.png'><br>public</div>
<div><img src='./social/ic_school_black_24dp.png'><br>school</div>
<div><img src='./social/ic_share_black_24dp.png'><br>share</div>
<div><img src='./social/ic_whatshot_black_24dp.png'><br>whatshot</div>
<h1>toggle</h1>
<div><img src='./toggle/ic_check_box_black_24dp.png'><br>check box</div>
<div><img src='./toggle/ic_check_box_outline_blank_black_24dp.png'><br>check box outline blank</div>
<div><img src='./toggle/ic_radio_button_off_black_24dp.png'><br>radio button off</div>
<div><img src='./toggle/ic_radio_button_on_black_24dp.png'><br>radio button on</div>
<div><img src='./toggle/ic_star_black_24dp.png'><br>star</div>
<div><img src='./toggle/ic_star_half_black_24dp.png'><br>star half</div>
<div><img src='./toggle/ic_star_outline_black_24dp.png'><br>star outline</div>

</body>
</html>

