<?php  //พ
header("Content-Type: text/css");
include ("../inc/config.inc.php");
?>/*    Generated by http://www.cssportal.com    */

@import url("reset.css");

body {
    font-family: Tahoma, Verdana, Arial, Helvetica, sans-serif;
    font-size: 13px;
    color:#333
}

p {
    padding: 10px;
}

#wrapper {
    width: 100%;
    min-width: 780px;
    max-width: 3000px;
    margin: 0 auto;
}

#headerwrap {
    width: 100%;
    float: left;
    margin: 0 auto;
}

#header {
    height: 75px;
    background: #FF6633;
    border-radius: 10px;
    border: 1px solid #d9d9d9;
    margin: 5px;

}

#contentliquid {
    float: left;
    width: 100%;
}

#contentwrap {
    width: calc(100% - 300px);
    /*margin-right: 300px;*/
    float: left;
}

#content {
    background: #FFFFFF;
    border-radius: 10px;
    border: 1px solid #ebebeb;
    margin: 5px;
	height: calc(100% - 100px);
}

#rightcolumnwrap {
    width: 300px;
    margin-left: -300px;
    float: left;
}

#rightcolumn {
    background: #F2F2F2;
    border-radius: 10px;
    border: 1px solid #dedede;
    margin: 5px;
	height: calc(100% - 100px);
	text-align: center;
}

